/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1Med;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author alisaid
 */
public class loginr extends javax.swing.JFrame {

    /**
     * Creates new form loginr
     */
    public loginr() {
        initComponents();
        loading();
       
        
        table.getTableHeader().setFont(new Font("Mshtakan",Font.BOLD, 13 ));
        table.getTableHeader().setForeground(Color.RED);
        
        table.getColumnModel().getColumn(3).setWidth(200);
        table.getColumnModel().getColumn(3).setMinWidth(200);
        table.getColumnModel().getColumn(3).setMaxWidth(200);
        
        table.getColumnModel().getColumn(2).setWidth(100);
        table.getColumnModel().getColumn(2).setMinWidth(100);
        table.getColumnModel().getColumn(2).setMaxWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        tablep = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        t2 = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        p6 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        ts = new javax.swing.JTextField();
        p4 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 178, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 178, -1));

        l3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l3.setText("Age");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 90, 26));

        l1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l1.setText("Patient name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 130, 30));

        r1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        r1.setText("Report");
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 50, 30));

        r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/knopf2.png"))); // NOI18N
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 80, 50));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Doctor", "Age", "Phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tablep.setViewportView(table);

        getContentPane().add(tablep, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 810, 210));

        t2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Manal Bajbouj", "Dr. Hussien Maatouk", "Dr. Elias Najjar", "Dr. Ziad Abdoh", "Dr. George Bechara", "Dr. Till Koetter", "Dr. Hisham Hammad", " " }));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 178, -1));

        l2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l2.setText("Doctor");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 216, -1, 30));

        l4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l4.setText("Phone number");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 276, 140, 30));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 178, -1));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 50, 40));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/löschen.png"))); // NOI18N
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 30, 40));

        back.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backG.png"))); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 70));

        b4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        b4.setText("Search");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 50, 40));

        ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsKeyReleased(evt);
            }
        });
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 178, -1));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-knopf-2-80.png"))); // NOI18N
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, -1, 40));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/spiral-notepad-pen-stethoscope-thermometer-gloves-white-surface.jpg"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1290, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) table.getModel();

        for(int i=0; i<=mod.getRowCount()-1;i= i+1){
            if(t1.getText().matches(mod.getValueAt(i, 0).toString()) && t3.getText().matches(mod.getValueAt(i, 2).toString())){

                new report().setVisible(true);
                this.dispose();

            }
        }

    }//GEN-LAST:event_r1MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        t1.setText(model.getValueAt(table.getSelectedRow(), 0).toString());
        t2.setSelectedItem(model.getValueAt(table.getSelectedRow(), 1).toString());
        t3.setText(model.getValueAt(table.getSelectedRow(), 2).toString());
        t4.setText(model.getValueAt(table.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_p6MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_p5MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setForeground(Color.black);
        back.setText("Back");
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setForeground(Color.red);
        back.setText("Go Back to Main");
    }//GEN-LAST:event_backMouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        // TODO add your handling code here:
        b4.setForeground(Color.black);

    }//GEN-LAST:event_b4MouseExited

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        // TODO add your handling code here:
        b4.setForeground(Color.BLUE);
    }//GEN-LAST:event_b4MouseEntered

    private void tsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsKeyReleased
        // TODO add your handling code here:
        {
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) table.getModel()));
            sorter.setRowFilter(RowFilter.regexFilter(ts.getText()));

            table.setRowSorter(sorter);
        }
    }//GEN-LAST:event_tsKeyReleased

       private void saving() {
    try{
    File file=new File(".\\src\\data.txt");
if(!file.exists()){
file.createNewFile() ;
}
    
    FileWriter fw =new FileWriter(file.getAbsoluteFile()) ;
    BufferedWriter bw = new BufferedWriter(fw);
    
    for(int i = 0 ;i < table.getRowCount();i++){
    for(int j = 0 ;j < table.getColumnCount();j++){
        bw.write((String)table.getModel().getValueAt(i , j)+"!@#");
    }
    bw.write("\n");
    }
    bw.close();
    fw.close();
    
    
    }catch(Exception ex){
        ex.printStackTrace();
    }
}
private void loading(){

    String line;
BufferedReader reader;
    try{       
        reader = new BufferedReader(new FileReader(".\\src\\data.txt"));
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        while((line = reader.readLine()) != null) 
        {
           model.addRow(line.split("!@#")); 
        }
        reader.close();
     }
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b4;
    private javax.swing.JLabel back;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel r;
    private javax.swing.JLabel r1;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablep;
    private javax.swing.JTextField ts;
    // End of variables declaration//GEN-END:variables
}
