/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1Med;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alisaid
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        loading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 185, -1));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 180, -1));

        b1.setText("Signup");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 130, -1));

        b4.setText("Login");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 124, -1));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-benutzeranmeldeinformationen-40-2.png"))); // NOI18N
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, 40, 60));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-passwort-40.png"))); // NOI18N
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, 40, 50));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/löschen.png"))); // NOI18N
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 30, 40));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 50, 40));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user", "pass"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 0));

        title.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Welcome in Ali Said's Medical Center");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 400, 100));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doctor-s-hand-holding-stethoscope-closeup.jpg"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 1280, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // DefaultTableModel model will not work because i used mod

        DefaultTableModel mod = (DefaultTableModel) tab.getModel();

        for(int i=0; i<=mod.getRowCount()-1;i= i+1){
            if(user.getText().matches(mod.getValueAt(i, 0).toString()) && pass.getText().matches(mod.getValueAt(i, 1).toString())){

                new main().setVisible(true);
                this.dispose();
            }

        }

    }//GEN-LAST:event_b4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_p6MouseClicked

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        new signup().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_b1MouseClicked

    private void saving() {
    try{
    File file=new File(".\\src\\user1.txt");
if(!file.exists()){
file.createNewFile() ;
}
    
    FileWriter fw =new FileWriter(file.getAbsoluteFile()) ;
    BufferedWriter bw = new BufferedWriter(fw);
    
    for(int i = 0 ;i < tab.getRowCount();i++){
    for(int j = 0 ;j < tab.getColumnCount();j++){
        bw.write((String)tab.getModel().getValueAt(i , j)+"!@#");
    }
    bw.write("\n");
    }
    bw.close();
    fw.close();
    
    
    }catch(Exception ex){
        ex.printStackTrace();
    }
}
private void loading(){

    String line;
BufferedReader reader;
    try{       
        reader = new BufferedReader(new FileReader(".\\src\\user1.txt"));
        DefaultTableModel model=(DefaultTableModel) tab.getModel();
        while((line = reader.readLine()) != null) 
        {
           model.addRow(line.split("!@#")); 
        }
        reader.close();
     }
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pic;
    private javax.swing.JTable tab;
    private javax.swing.JLabel title;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
