/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1Med;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author alisaid
 */
public class table extends javax.swing.JFrame {

    /**
     * Creates new form table
     */
    public table() {
        initComponents();
        loading();
        table.setOpaque(false);
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setOpaque(false);
        table.setShowGrid(false);
        tablep.setOpaque(false);
        tablep.getViewport().setOpaque(false);
        
        table.getTableHeader().setFont(new Font("Mshtakan",Font.BOLD, 18 ));
        table.getTableHeader().setForeground(Color.black);
        
        table.getColumnModel().getColumn(3).setWidth(200);
        table.getColumnModel().getColumn(3).setMinWidth(200);
        table.getColumnModel().getColumn(3).setMaxWidth(200);
        
        table.getColumnModel().getColumn(2).setWidth(100);
        table.getColumnModel().getColumn(2).setMinWidth(100);
        table.getColumnModel().getColumn(2).setMaxWidth(100);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JComboBox<>();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        tablep = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        ts = new javax.swing.JTextField();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 178, -1));

        t2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Manal Bajbouj", "Dr. Hussien Maatouk", "Dr. Elias Najjar", "Dr. Ziad Abdoh", "Dr. George Bechara", "Dr. Till Koetter", "Dr. Hisham Hammad", " " }));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 178, -1));

        l1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l1.setText("Name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, 65, 26));

        l2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l2.setText("Doctor");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 180, 26));

        l3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l3.setText("Age");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 65, 26));

        l4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l4.setText("Phone number");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 140, 26));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 178, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 178, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Doctor", "Age", "Phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tablep.setViewportView(table);

        getContentPane().add(tablep, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 330, 810, -1));

        b1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        b1.setText("Add");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, 50, 40));

        b2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        b2.setText("Delete");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 50, 40));

        b3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        b3.setText("Update");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 60, 40));

        b4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        b4.setText("Search");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 50, 40));

        ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsKeyReleased(evt);
            }
        });
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 178, -1));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-knopf-2-80.png"))); // NOI18N
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 90, 40));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-knopf-2-80.png"))); // NOI18N
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 80, 40));

        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-knopf-2-80.png"))); // NOI18N
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 60));

        p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-knopf-2-80.png"))); // NOI18N
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 40));

        p5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/löschen.png"))); // NOI18N
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 30, 40));

        p6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 50, 40));

        back.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backG.png"))); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 70));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doctors-stethoscope-white-background.jpg"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
           DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        //model.addRow(new Object [] {Here we add all the informations in a single row});
        
        model.addRow(new Object [] {t1.getText(),t2.getSelectedItem().toString(), t3.getText(), t4.getText() });
         clear();
         saving();
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        model.removeRow(table.getSelectedRow());
         clear();
         saving();
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) table.getModel();
         
         model.setValueAt(t4.getText(), table.getSelectedRow(), 3);
         model.setValueAt(t3.getText(), table.getSelectedRow(), 2);
         model.setValueAt(t2.getSelectedItem().toString(), table.getSelectedRow(), 1);
         model.setValueAt(t1.getText(), table.getSelectedRow(), 0);
         clear();
         saving();
    }//GEN-LAST:event_b3MouseClicked

    private void tsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsKeyReleased
        // TODO add your handling code here:
                     {                                            
    TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) table.getModel())); 
    sorter.setRowFilter(RowFilter.regexFilter(ts.getText()));

    table.setRowSorter(sorter);
}
    }//GEN-LAST:event_tsKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) table.getModel();
         t1.setText(model.getValueAt(table.getSelectedRow(), 0).toString());
         t2.setSelectedItem(model.getValueAt(table.getSelectedRow(), 1).toString());
         t3.setText(model.getValueAt(table.getSelectedRow(), 2).toString());
         t4.setText(model.getValueAt(table.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setForeground(Color.BLUE);
    }//GEN-LAST:event_b1MouseEntered

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        // TODO add your handling code here:
        b3.setForeground(Color.BLUE);
    }//GEN-LAST:event_b3MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setForeground(Color.black);
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        // TODO add your handling code here:
        b2.setForeground(Color.BLUE);
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        // TODO add your handling code here:
        b2.setForeground(Color.black);
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        // TODO add your handling code here:
        b3.setForeground(Color.black);
    }//GEN-LAST:event_b3MouseExited

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_p6MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setForeground(Color.black);
        back.setText("Back");
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setForeground(Color.red);
        back.setText("Go Back to Main");

    }//GEN-LAST:event_backMouseEntered

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        // TODO add your handling code here:
        b4.setForeground(Color.BLUE);
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        // TODO add your handling code here:
        b4.setForeground(Color.black);
        
    }//GEN-LAST:event_b4MouseExited

    
    public void clear(){
    t4.setText("");
    t3.setText("");
    t2.setSelectedItem("Dr. Manal Bajbouj");
    t1.setText("");
    }
    private void saving() {
    try{
    File file=new File(".\\src\\data.txt");
if(!file.exists()){
file.createNewFile() ;
}
    
    FileWriter fw =new FileWriter(file.getAbsoluteFile()) ;
    BufferedWriter bw = new BufferedWriter(fw);
    
    for(int i = 0 ;i < table.getRowCount();i++){
    for(int j = 0 ;j < table.getColumnCount();j++){
        bw.write((String)table.getModel().getValueAt(i , j)+"!@#");
    }
    bw.write("\n");
    }
    bw.close();
    fw.close();
    
    
    }catch(Exception ex){
        ex.printStackTrace();
    }
}
private void loading(){

    String line;
BufferedReader reader;
    try{       
        reader = new BufferedReader(new FileReader(".\\src\\data.txt"));
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        while((line = reader.readLine()) != null) 
        {
           model.addRow(line.split("!@#")); 
        }
        reader.close();
     }
    catch(IOException e){
        JOptionPane.showMessageDialog(null, "Error");
e.printStackTrace();

    }
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel back;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablep;
    private javax.swing.JTextField ts;
    // End of variables declaration//GEN-END:variables
}
